### ISSUE TITLE
Questions about building for Linux desktop x86_64 (and later for Android)

### ISSUE THREAD

**Issue by kaphula** [cmatsuoka/libxmp-java#1]
Hello,

I would like to start by saying that this is the first day I am learning about NDK in general, so bear with me here.

I am interested in using this library to play XM music files in my Desktop/Android game that has been built on top of libGDX. I am trying to get this example to play some modules first on my Desktop (Linux x86_64), and after that works, I will try to include this playback library to my game project.

I cannot get the example player to work on desktop because I get this error message about invalid ELF header `libxmp-jni.so: /usr/lib/libc.so: invalid ELF header`:
```
> java -Djava.library.path=./libs/x86_64/ -jar player.jar unwholesome.mod

Exception in thread "main" java.lang.UnsatisfiedLinkError: $HOME/src/github/libxmp-java/libxmp/libs/x86_64/libxmp-jni.so: /usr/lib/libc.so: invalid ELF header
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1946)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1861)
        at java.lang.Runtime.loadLibrary0(Runtime.java:871)
        at java.lang.System.loadLibrary(System.java:1124)
        at org.helllabs.libxmp.Xmp.<clinit>(Unknown Source)
        at org.helllabs.libxmp.Player.<init>(Unknown Source)
        at org.helllabs.libxmp.Player.<init>(Unknown Source)
        at com.example.ModPlayer.run(Unknown Source)
        at com.example.ModPlayer.main(Unknown Source)
```
Here's a quick summary of how I built `Libxmp.jar` and `player.jar`. I tried to follow the README's instructions but they were not very specific.

First I downloaded the libxmp and I modified its `Application.mk` with change:
```
APP_ABI          := armeabi-v7a x86 x86_64
```
Then I file ran `ndk-build` at `libxmp/jni`. This generated the native static libraries (.a files) that are needed to build `libxmp-java` I suppose.

Next I added the same changes to `libxmp-java`'s `Application.mk` file as with `libxmp`. Then I ran `ndk-build` in `libxmp-java/libxmp/jni`. This gave me the native libraries at `libxmp-java/libxmp/libs` for these platforms: `armeabi-v7a  x86  x86_64`.

After that I ran `ant` in `libxmp-java/libxmp/` to get the `Libxmp.jar` file. Next I did the same in `libxmp-java/examples/player/` to get the `player.jar`. I then moved the `player.jar` to `libxmp-java/libxmp/` and ran it with the command seen in the beginning of this message.

Is the `x86_64` I added manually in fact for Android only and that's why I get the ELF error message when I try to run `player.jar`? How can I build `libxmp` and `libxmp-java` correctly so that I can use the `player.jar` on my desktop Linux x86_64? 

**EDIT 1:**
So I actually realized that in order to build `libxmp-jni` I have to run the Makefile at `libxmp-java/libxmp/jni/Makefile`. This generates the desktop version of `libxmp-jni.so` with correct ELF symbols.

The problem now is that once I try to run the `player.jar` with this shared library, I get this error:
```
Libxmp player test
java: symbol lookup error: $HOME/libxmp-java/libxmp/jni/libxmp-jni.so: undefined symbol: xmp_create_context
```

**EDIT 2**

I got the `player.jar` to play modules on desktop by using the [system installed version](https://aur.archlinux.org/packages/libxmp/) of `libxmp` to build the `libxmp-jni.so`.

Something is not right here, though. The playback is not comparable to what can be heard from [xmp-cli](https://github.com/cmatsuoka/xmp-cli). The `player.jar` version does not trigger some of the notes correctly, so certain parts of the song are silent. I wonder what is going on here?

**Comment by cmatsuoka** [comment]
Hmm. Could you try it using a locally built version of the library, to rule out problems related to mismatched versions or build options in the system library?

**Comment by kaphula** [comment]
When I build `libxmp-jni` using the locally built `libxmp`'s shared libraries, running the `player.jar` gives this same error:
```
Libxmp player test
java: symbol lookup error: $HOME/libxmp-java/libxmp/jni/libxmp-jni.so: undefined symbol: xmp_create_context
```
Running `xmp-cli` with the locally build shared libraries works and plays the module file correctly.

Can you explain what is the purpose of `Libxmp.jar` file and how should it be used?

And another thing, which OpenJDK version should I include in`libxmp-java/libxmp/jni/Makefile`? I am currently using this path: `JAVADIR=/usr/lib/jvm/java-8-openjdk/include`

**EDIT:**
When I get the mod playing using the system built version of libxmp, `player.jar` mutes channels 2 and 3 out of the 4 in the module file in question, so that's why the playback sound weird. I confirmed this by playing the module in a tracker with channels 2 and 3 muted and it sounds the same.

**Comment by kaphula** [comment]
Quick update here. I got the module to trigger/play all of its samples with these settings on `AudioPlay.java`:
```
	public AudioPlay(final float freq) throws LineUnavailableException {
		final boolean isBigEndian = ByteOrder.nativeOrder() == ByteOrder.BIG_ENDIAN;
                float srate = 44100.0f;
		// final AudioFormat format = new AudioFormat(srate, 16, 2, true, isBigEndian);
		final AudioFormat format = new AudioFormat(srate, 16, 1, true, isBigEndian);
		final DataLine.Info info = new DataLine.Info(SourceDataLine.class, format);
...
```
The important change here is setting the AudioFormat to play in mono. However, the module playback speed gets very slow if it is set to mono.

**Comment by kaphula** [comment]
Sorry for spamming this issue, but I am somewhat lost with this library despite having read the docs and studied example code, and I don't know a better place to ask help.

I downloaded and ran [xmp-android](https://github.com/cmatsuoka/xmp-android) on Android Studio and it worked nicely. I compiled `xmp-jni` shared libs using the latest libxmp release. I uploaded a song to android emulator using adb and the emulator plays the song. All good!

Next I created my own Android project and tried to use the same jni source files from `xmp-jni` to get some songs loaded and playing. I built the libs same way as with `xmp-android` and included them to my project. Below is the source code listing of my MainActivity. Using debugger it seems that `Xmp.init(44100, 400)` does not return error, although I am not sure if the context creation succeeds since there's no error checking for it in `xmp-jni.c`. `Xmp.loadModule` returns `-6` as an error value however. From the docs, this indicates `XMP_ERROR_SYSTEM     /* System error */`

I wonder what might be the cause since I am basically doing the exact same thing as with `xmp-android`, which builds and works fine on my physical phone and on the emulator.

```kotlin
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        var t = "OK!"
        if (!Xmp.init(44100,400)) // init ok!
            t = "NO!"

        setPlayer(Xmp.PLAYER_DEFPAN, 50)
        val ret = Xmp.loadModule("/storage/emulated/0/mod/music.xm") // load returns -6
        if (ret != 0)
            t = "NO!"

        Xmp.startPlayer(44100)

        // setPlayer(Xmp.PLAYER_SMPCTL, Xmp.SMPCTL_SKIP)
        setPlayer(Xmp.PLAYER_MIX, 100)
        setPlayer(Xmp.DSP_LOWPASS, Xmp.DSP_LOWPASS)
        setPlayer(Xmp.PLAYER_AMP, 1)
        setPlayer(Xmp.PLAYER_INTERP, Xmp.INTERP_LINEAR)
        setPlayer(Xmp.PLAYER_DSP, Xmp.DSP_LOWPASS)

        Xmp.playAudio()
        Xmp.deinit()
        sample_text.text = t // stringFromJNI()
    }

    /**
     * A native method that is implemented by the 'native-lib' native library,
     * which is packaged with this application.
     */
    external fun stringFromJNI(): String

    companion object {
        // Used to load the 'native-lib' library on application startup.
        init {
            System.loadLibrary("hello-jni")
            System.loadLibrary("xmp-jni")
        }
    }
}

```

**Comment by Dunnysoft** [comment]
Hi Kaphula, I was wondering if you've had any success?  I and another LibGDX user have been talking about getting module music working in LibGDX games and I've been doing some digging.  Unfortunately my skillbase is very low and my C/C++ knowledge is extremely rusty, and I'm finding it difficult to understand how to build JNI libraries.  I'm working in a Win64 environment.

**Comment by kaphula** [comment]
Unfortunately, I was not able to get this to work. I eventually gave up and moved on to other things. As you can see from my last post, I was trying demo the native playback of libxmp on a fresh Android project (without LibGDX), but even then the library failed to load the xm module although the initialization seemed work. All I can say it was not very simple. I think in addition to knowledge of C you need some knowledge of how to use Makefiles, NDK-build scrips or CMake depending on which way you compile and include the native libs to your Java project. There are many things to consider and it seems things can go easily wrong if you are not familiar with these things.

If you choose to go through this and get it to work, let us know. I wish you good luck!

**Comment by Dunnysoft** [comment]
Thanks for the update.  Based on your answer I might try and use libgdx-jnigen as I've already had a bit of a play with it and I think that might be the easiest way to get it to build JNI for all platforms.

Out of all the mod playing libraries I've found, XMPlay looks the most promising, I was trying out JavaMod but it lacked accuracy with .IT files, and libopenmpt is incredibly complex and I just don't get it :).  The alternative to that is perhaps borrowing the code from Droidsound (who has already adapted libopenmpt to JNI) but that will still require a bit of work

**Comment by TheEssem** [comment]
I've created a fork of this repo that converts it into a Gradle project and builds libxmp automatically, among some other changes. This should greatly simplify the build process on x86 and amd64 systems; however, ARM support is still WIP: https://github.com/TheEssem/libxmp-java
